apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
       template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command:
          - sh
          - -c
          - >
            echo "Waiting for mysql-service:3306...";
            until nc -z mysql-service 3306;
            do
              echo "MySQL not ready, waiting...";
              sleep 2;
            done;
            echo "MySQL is ready!";
      containers:
      - name: {{ .Values.applicationName }}
        image: {{ .Values.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort:  {{ .Values.containerPort}}
        # Liveness Probe
        livenessProbe:
          httpGet:
            path:  {{ .Values.livenessProbePath}}
            port:  {{ .Values.containerPort}}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        # Readiness Probe
        readinessProbe:
          httpGet:
            path:  {{ .Values.livenessProbePath}}
            port:  {{ .Values.containerPort}}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits: 
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
