deployment:
  applicationName: mf-node-app
  replicaCount: 3
  dockerImage: malcolmcfraser/mf-node-app-template:latest
  imagePullPolicy: Always
  containerPort: 3000
  livenessProbePath: /health
  readinessProbePath: /ready
  mysqlWaitImage: busybox
  mysqlHost: mysql-service
  mysqlPort: 3306

service:
  port: 3000
